name: 🐛 Bug Report
description: Create a report to help us improve ugit
labels: ["bug"]
assignees:
  - Bhupesh-V
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see! Any log outputs, demo screenshots
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: ugit-version
    attributes:
      label: Ugit Version
      description: What version of ugit are you running?
      options:
        - v5.1 (Latest)
        - v5.0
        - v4.1
        - v4.0
        - v3.0
        - v2.0
        - v1.0
    validations:
      required: true
  - type: dropdown
    id: bash-version
    attributes:
      label: Bash Version
      description: What version of bash are you running?
      options:
        - Bash >= 5.0
        - Bash >= 4.0
        - Bash >= 3.0
    validations:
      required: true
  - type: textarea
    id: git-version
    attributes:
      label: Git Version
      description: Please paste the output of `git --version`
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What OS are you seeing the problem on?
      multiple: false
      options:
        - Linux Based
        - MacOS
        - Windows
    validations:
      required: true
  - type: textarea
    id: terminalName
    attributes:
      label: Terminal Name
      description: Please specify the name of terminal you are using (E.g Kitty, iterm2 etc.)
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Bhupesh-V/ugit/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
