name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux-test:
    name: Linux Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Disable initramfs update
      run: sudo sed -i 's/yes/no/g' /etc/initramfs-tools/update-initramfs.conf
    - name: Disable man-db update
      run: sudo rm -f /var/lib/man-db/auto-update
    - name: Disable fontconfig trigger
      run: sudo sed '/fontconfig/d' -i /var/lib/dpkg/triggers/File
    - name: Disable install-info trigger
      run: sudo sed '/install-info/d' -i /var/lib/dpkg/triggers/File
    - name: Disable mime related triggers
      run: sudo sed '/mime/d' -i /var/lib/dpkg/triggers/File
    - name: Disable hicolor icon theme triggers
      run: sudo sed '/hicolor-icon-theme/d' -i /var/lib/dpkg/triggers/File
    - name: ShellCheck Test
      run: shellcheck ugit
    - name: Syntax Testing
      # -n : read  commands  but  do  not  execute  them.  
      #      This may be used to check a shell script for syntax errors (ignored by interactive shells).
      run : |
          bash -n ugit
